remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: true
 executive: true

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: true
 week: true
 24 hours: true

positions:
  - senior machine learning engineer
  - Machine Learning Engineer
  - ai
  - Python Developer
  - llm

locations:
  - Canada
  - USA

apply_once_at_company: true

distance: 100

companyBlacklist:
  - Crossover
  - Lumenalta (formerly Clevertech)
  - RemoteWorker CA
  - hackajob
  - HireMeFast LLC
  - HireRoad
  - Dice
  - YO HR Consultancy
  - wayfair
titleBlacklist:
  - Juniors
  - Junior
  - Project Manager
  - Project
  - salesforce
  - customer
  - netsuite
  - Product Manager
  - W2
  - Director
  - Writer

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'