remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: true
 executive: true

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: true
 24 hours: true

positions:
  - senior machine learning engineer
  - Machine Learning Engineer
  - ai
  - Data Science
  - Data Analyst
  - Python Developer
  - High Frequency Trading
  - Quant Trading
  - Quant Developer

locations:
  - Canada
  - USA
  - UAE
  - Japan

distance: 100

companyBlacklist:
  - Crossover
  - Lumenalta (formerly Clevertech)
  - RemoteWorker CA
  - hackajob
  - HireMeFast LLC
  - HireRoad
  - Dice
  - YO HR Consultancy
titleBlacklist:
  - Juniorss